; bios_table.asm - GENERATED by diag/tools/gen_bios_table.py, do not edit
;   CRC32 of 32 KB MSX main ROMs -> name.  dw name, db crc32 LE; dw 0 ends
biosTable:
    dw sBt0
    db 0x34, 0x01, 0x87, 0x00       ; 00870134 HB-F1XDJ, HB-F1XDJ
    dw sBt1
    db 0xAB, 0x4F, 0xAD, 0x01       ; 01AD4FAB TALENT DPC-200
    dw sBt2
    db 0xE0, 0x35, 0x11, 0x07       ; 071135E0 FS-4000
    dw sBt3
    db 0x77, 0x0D, 0x61, 0x07       ; 07610D77 EXPERT 1.0
    dw sBt4
    db 0x13, 0x2E, 0x6E, 0x0A       ; 0A6E2E13 AX500-BIOS-BASIC
    dw sBt5
    db 0x99, 0x6B, 0x2D, 0x0C       ; 0C2D6B99 C-BIOS MSX2 JP, C-BIOS MSX2 JP
    dw sBt6
    db 0x17, 0xF8, 0xC7, 0x0C       ; 0CC7F817 ML-G1 ES, ML-G3 ES
    dw sBt7
    db 0x4E, 0xF9, 0xAE, 0x0D       ; 0DAEF94E C-BIOS MSX2 BR, C-BIOS MSX2 BR
    dw sBt8
    db 0xD8, 0x8D, 0x48, 0x0F       ; 0F488DD8 HB-101P, HB-10P, HB-201P, HB-501P, HB-101P, HB-10P, HB-201P, HB-501P
    dw sBt9
    db 0xAD, 0xDD, 0xF7, 0x12       ; 12F7DDAD C-BIOS MSX2, C-BIOS MSX2
    dw sBt10
    db 0x5C, 0xEB, 0xDD, 0x15       ; 15DDEB5C HB-20P, HB-20P
    dw sBt11
    db 0xDE, 0x03, 0xE5, 0x15       ; 15E503DE CF-2700 GB, CF-2700 GB
    dw sBt12
    db 0x08, 0x16, 0x77, 0x19       ; 19771608 FS-A1FX, FS-A1WX, FS-A1FX, FS-A1WX, PHC-70FD2
    dw sBt13
    db 0x6C, 0x24, 0xE9, 0x1C       ; 1CE9246C SVI-728
    dw sBt14
    db 0x02, 0x5B, 0xD9, 0x22       ; 22D95B02 C-BIOS MSX2+ JP, C-BIOS MSX2+ JP
    dw sBt15
    db 0x7B, 0x4A, 0x46, 0x24       ; 24464A7B BRUC100 2
    dw sBt16
    db 0x96, 0xF5, 0x1C, 0x28       ; 281CF596 NIKKO PC-70100 B
    dw sBt17
    db 0xA3, 0x77, 0x6D, 0x29       ; 296D77A3 C-BIOS MSX1 JP, C-BIOS MSX1 JP
    dw sBt18
    db 0x7B, 0xD2, 0x7E, 0x2C       ; 2C7ED27B F1XVBIOS, F1XVBIOS
    dw sBt19
    db 0xAA, 0x4B, 0x9D, 0x2E       ; 2E9D4BAA C-BIOS MSX1 EU, C-BIOS MSX1 EU
    dw sBt20
    db 0x39, 0xA6, 0x3A, 0x31       ; 313AA639 728SEBIOS
    dw sBt21
    db 0x47, 0xC5, 0x8E, 0x35       ; 358EC547 FS-A1WSX, FS-A1WSX, PHC-35J
    dw sBt22
    db 0xF7, 0xE0, 0x91, 0x38       ; 3891E0F7 HX-33
    dw sBt23
    db 0x3B, 0xCD, 0xB0, 0x3A       ; 3AB0CD3B DPC-100, DPC-180, DPC-200, FC80UBIOS
    dw sBt24
    db 0x03, 0xDC, 0x08, 0x3B       ; 3B08DC03 MPC2
    dw sBt25
    db 0x7D, 0x82, 0xB2, 0x3B       ; 3BB2827D CX5MII-128
    dw sBt26
    db 0xF5, 0x8B, 0x1B, 0x43       ; 431B8BF5 738PBIOS
    dw sBt27
    db 0x7B, 0x89, 0x4F, 0x43       ; 434F897B HB-11
    dw sBt28
    db 0x82, 0xC8, 0x32, 0x45       ; 4532C882 C-BIOS MSX1, C-BIOS MSX1
    dw sBt29
    db 0xF4, 0x94, 0xA1, 0x4A       ; 4AA194F4 CF-2700 GERMAN, CF-2700 GERMAN
    dw sBt30
    db 0xAA, 0x2C, 0x7B, 0x50       ; 507B2CAA CX5MII BASIC-BIO
    dw sBt31
    db 0x07, 0x09, 0x85, 0x53       ; 53850907 CPC-300, CPC-400S
    dw sBt32
    db 0x11, 0xB7, 0x86, 0x54       ; 5486B711 HX-10
    dw sBt33
    db 0x07, 0x34, 0xD0, 0x5A       ; 5AD03407 CF-1200, CF-2700, CF-3000, CF-3300, FS-1300
    dw sBt34
    db 0x13, 0x8E, 0xF3, 0x5B       ; 5BF38E13 FS-5500
    dw sBt35
    db 0xED, 0x5C, 0xD3, 0x5C       ; 5CD35CED AX350IIF
    dw sBt36
    db 0x70, 0x8B, 0xCB, 0x5D       ; 5DCB8B70 AX150 XC276 A 0
    dw sBt37
    db 0x18, 0xAF, 0x3C, 0x5E       ; 5E3CAF18 NMS8250-16
    dw sBt38
    db 0x02, 0x48, 0xC2, 0x61       ; 61C24802 C-BIOS MSX1 BR, C-BIOS MSX1 BR
    dw sBt39
    db 0xCE, 0x7D, 0x86, 0x62       ; 62867DCE ML-FX1
    dw sBt40
    db 0xA6, 0x17, 0xE1, 0x68       ; 68E117A6 BIOS
    dw sBt41
    db 0xA5, 0xF3, 0xDA, 0x6C       ; 6CDAF3A5 NMS8220, NMS8245, NMS8250
    dw sBt42
    db 0x75, 0x9B, 0x75, 0x6E       ; 6E759B75 C-BIOS MSX2 EU, C-BIOS MSX2 EU
    dw sBt43
    db 0x45, 0x2D, 0xCE, 0x70       ; 70CE2D45 VG8020F
    dw sBt44
    db 0xB9, 0x7F, 0x84, 0x71       ; 71847FB9 728DKBIOS
    dw sBt45
    db 0xCA, 0xE1, 0xF0, 0x74       ; 74F0E1CA C-BIOS MSX2+ BR, C-BIOS MSX2+ BR
    dw sBt46
    db 0xC4, 0x8C, 0xF1, 0x75       ; 75F18CC4 VG8235 DE
    dw sBt47
    db 0x81, 0xE3, 0xC5, 0x76       ; 76C5E381 SVI-728ES
    dw sBt48
    db 0x80, 0xE0, 0x73, 0x79       ; 7973E080 CX5MII-128 GERRI
    dw sBt49
    db 0xDD, 0x32, 0x2B, 0x7E       ; 7E2B32DD HB-75D, HB-75D
    dw sBt50
    db 0x5E, 0x79, 0x05, 0x82       ; 8205795E FC-200, VG8020, HX-51I
    dw sBt51
    db 0x77, 0x9E, 0xC3, 0x83       ; 83C39E77 MB-H70
    dw sBt52
    db 0x20, 0x03, 0x72, 0x88       ; 88720320 738DKBIOS
    dw sBt53
    db 0x45, 0xE8, 0xD3, 0x8C       ; 8CD3E845 TPC-310
    dw sBt54
    db 0xD6, 0xD6, 0x9A, 0x95       ; 959AD6D6 C-BIOS MSX2+ EU, C-BIOS MSX2+ EU
    dw sBt55
    db 0xC0, 0x07, 0x9F, 0x99       ; 999F07C0 HB-75F
    dw sBt56
    db 0x97, 0x7B, 0x3E, 0x9B       ; 9B3E7B97 FS-A1, FS-A1F, FS-A1FM, FS-A1MK2, HB-F1, HB-F1II, HB-F5, HB-F900, HC-95A NORMAL, FS-4500, FS-4600, FS-4700, FS-A1, FS-A1F, FS-A1FM, FS-A1MK2, HB-F1, HB-F1II, HB-F5, HB-F900
    dw sBt57
    db 0xCE, 0xB1, 0x0B, 0xA1       ; A10BB1CE EXPERTTURBO
    dw sBt58
    db 0x3D, 0x56, 0x7C, 0xA2       ; A27C563D UC-V102
    dw sBt59
    db 0xB4, 0xE6, 0x17, 0xA3       ; A317E6B4 VG8020-20
    dw sBt60
    db 0x07, 0xA7, 0x4E, 0xA4       ; A44EA707 FS-5000
    dw sBt61
    db 0x62, 0x7D, 0x00, 0xAD       ; AD007D62 SVI-738
    dw sBt62
    db 0x41, 0x83, 0x1E, 0xAE       ; AE1E8341 ML-TS2
    dw sBt63
    db 0x1D, 0x85, 0x1C, 0xB3       ; B31C851D HB-F500P, HB-F700P, HB-F9P, HB-G900P, VG8230, HB-F500P, HB-F700P, HB-F9P, HB-G900P
    dw sBt64
    db 0x94, 0x26, 0x94, 0xB6       ; B6942694 HOTBIT 1.1
    dw sBt65
    db 0xD7, 0xEF, 0x49, 0xB7       ; B749EFD7 FM-X
    dw sBt66
    db 0xDD, 0xB3, 0x81, 0xBA       ; BA81B3DD HB-F1XD, PHC-23JB, HB-F1XD
    dw sBt67
    db 0x36, 0xC4, 0x95, 0xBD       ; BD95C436 AX170
    dw sBt68
    db 0x33, 0x15, 0xE2, 0xBE       ; BEE21533 NMS8250-19
    dw sBt69
    db 0x50, 0x7A, 0x57, 0xC0       ; C0577A50 HB-F700F, HB-F700F
    dw sBt70
    db 0xEF, 0x68, 0xA8, 0xC3       ; C3A868EF CPC-51 BASIC-BIO
    dw sBt71
    db 0x98, 0x42, 0xBC, 0xC7       ; C7BC4298 BRUC100 1
    dw sBt72
    db 0xA0, 0xDA, 0xCC, 0xC8       ; C8CCDAA0 SVI-738 SE, SVI-738 SE
    dw sBt73
    db 0x30, 0x8B, 0xE9, 0xCA       ; CAE98B30 AX200
    dw sBt74
    db 0x52, 0x1D, 0xE1, 0xD1       ; D1E11D52 FS-TM1
    dw sBt75
    db 0x66, 0x0D, 0x11, 0xD2       ; D2110D66 PHC-28L
    dw sBt76
    db 0xCA, 0xC9, 0x57, 0xDF       ; DF57C9CA VG8010F
    dw sBt77
    db 0x53, 0x2B, 0x24, 0xE2       ; E2242B53 CX5MU
    dw sBt78
    db 0x3C, 0x6B, 0xCF, 0xE5       ; E5CF6B3C PHC-28S
    dw sBt79
    db 0x5C, 0xD5, 0x51, 0xE7       ; E751D55C YIS503IIR BASIC-
    dw sBt80
    db 0x29, 0x8E, 0xD0, 0xE7       ; E7D08E29 YIS503III
    dw sBt81
    db 0x0E, 0x90, 0x18, 0xE9       ; E918900E C-BIOS MSX2+, C-BIOS MSX2+
    dw sBt82
    db 0x8E, 0xB0, 0x41, 0xE9       ; E941B08E V-8
    dw sBt83
    db 0x79, 0xAA, 0x75, 0xE9       ; E975AA79 HB-F700D, HB-G900D, HB-F700D, HB-G900D
    dw sBt84
    db 0x89, 0xD7, 0xCC, 0xE9       ; E9CCD789 HB-55P, HB-75P, V-20, HC-7GB, ML-F80, MPC100, HB-55P, HB-75P, CX5M
    dw sBt85
    db 0x55, 0x61, 0x30, 0xEA       ; EA306155 AX350II
    dw sBt86
    db 0x90, 0x93, 0x22, 0xEE       ; EE229390 HB-10, CF-2000, PX-V60, HB-10, HB-701
    dw sBt87
    db 0x72, 0xB9, 0xB4, 0xEF       ; EFB4B972 EXPERT 1.1, EXPERT DDPLUS, EXPERT PLUS
    dw sBt88
    db 0xB0, 0x70, 0xD9, 0xEF       ; EFD970B0 VG8000, VG8010
    dw sBt89
    db 0x18, 0xD5, 0x5E, 0xF0       ; F05ED518 VG8235
    dw sBt90
    db 0xB9, 0xCB, 0xC0, 0xF0       ; F0C0CBB9 738SPBIOS
    dw sBt91
    db 0x1B, 0x31, 0x65, 0xF4       ; F465311B HB-F9P RUSSIAN, HB-F9P RUSSIAN
    dw sBt92
    db 0x0C, 0x4A, 0x9A, 0xF5       ; F59A4A0C HOTBIT 1.2
    dw sBt93
    db 0xE8, 0x5E, 0x29, 0xF6       ; F6295EE8 VG8240
    dw sBt94
    db 0x61, 0x94, 0x08, 0xFA       ; FA089461 NMS801
    dw sBiosGoauld
    db 0xE6, 0xAC, 0x09, 0x83       ; 8309ACE6 Goa'uld internal MSX2+ main ROM
    dw 0
sBt0: db "HB-F1XDJ+", 0
sBt1: db "TALENT DPC-200", 0
sBt2: db "FS-4000", 0
sBt3: db "EXPERT 1.0", 0
sBt4: db "AX500-BIOS-BASIC", 0
sBt5: db "C-BIOS MSX2 JP+", 0
sBt6: db "ML-G1 ES+", 0
sBt7: db "C-BIOS MSX2 BR+", 0
sBt8: db "HB-101P+", 0
sBt9: db "C-BIOS MSX2+", 0
sBt10: db "HB-20P+", 0
sBt11: db "CF-2700 GB+", 0
sBt12: db "FS-A1FX+", 0
sBt13: db "SVI-728", 0
sBt14: db "C-BIOS MSX2+ JP+", 0
sBt15: db "BRUC100 2", 0
sBt16: db "NIKKO PC-70100 B", 0
sBt17: db "C-BIOS MSX1 JP+", 0
sBt18: db "F1XVBIOS+", 0
sBt19: db "C-BIOS MSX1 EU+", 0
sBt20: db "728SEBIOS", 0
sBt21: db "FS-A1WSX+", 0
sBt22: db "HX-33", 0
sBt23: db "DPC-100+", 0
sBt24: db "MPC2", 0
sBt25: db "CX5MII-128", 0
sBt26: db "738PBIOS", 0
sBt27: db "HB-11", 0
sBt28: db "C-BIOS MSX1+", 0
sBt29: db "CF-2700 GERMAN+", 0
sBt30: db "CX5MII BASIC-BIO", 0
sBt31: db "CPC-300+", 0
sBt32: db "HX-10", 0
sBt33: db "CF-1200+", 0
sBt34: db "FS-5500", 0
sBt35: db "AX350IIF", 0
sBt36: db "AX150 XC276 A 0", 0
sBt37: db "NMS8250-16", 0
sBt38: db "C-BIOS MSX1 BR+", 0
sBt39: db "ML-FX1", 0
sBt40: db "BIOS", 0
sBt41: db "NMS8220+", 0
sBt42: db "C-BIOS MSX2 EU+", 0
sBt43: db "VG8020F", 0
sBt44: db "728DKBIOS", 0
sBt45: db "C-BIOS MSX2+ BR+", 0
sBt46: db "VG8235 DE", 0
sBt47: db "SVI-728ES", 0
sBt48: db "CX5MII-128 GERRI", 0
sBt49: db "HB-75D+", 0
sBt50: db "FC-200+", 0
sBt51: db "MB-H70", 0
sBt52: db "738DKBIOS", 0
sBt53: db "TPC-310", 0
sBt54: db "C-BIOS MSX2+ EU+", 0
sBt55: db "HB-75F", 0
sBt56: db "FS-A1+", 0
sBt57: db "EXPERTTURBO", 0
sBt58: db "UC-V102", 0
sBt59: db "VG8020-20", 0
sBt60: db "FS-5000", 0
sBt61: db "SVI-738", 0
sBt62: db "ML-TS2", 0
sBt63: db "HB-F500P+", 0
sBt64: db "HOTBIT 1.1", 0
sBt65: db "FM-X", 0
sBt66: db "HB-F1XD+", 0
sBt67: db "AX170", 0
sBt68: db "NMS8250-19", 0
sBt69: db "HB-F700F+", 0
sBt70: db "CPC-51 BASIC-BIO", 0
sBt71: db "BRUC100 1", 0
sBt72: db "SVI-738 SE+", 0
sBt73: db "AX200", 0
sBt74: db "FS-TM1", 0
sBt75: db "PHC-28L", 0
sBt76: db "VG8010F", 0
sBt77: db "CX5MU", 0
sBt78: db "PHC-28S", 0
sBt79: db "YIS503IIR BASIC-", 0
sBt80: db "YIS503III", 0
sBt81: db "C-BIOS MSX2++", 0
sBt82: db "V-8", 0
sBt83: db "HB-F700D+", 0
sBt84: db "HB-55P+", 0
sBt85: db "AX350II", 0
sBt86: db "HB-10+", 0
sBt87: db "EXPERT 1.1+", 0
sBt88: db "VG8000+", 0
sBt89: db "VG8235", 0
sBt90: db "738SPBIOS", 0
sBt91: db "HB-F9P RUSSIAN+", 0
sBt92: db "HOTBIT 1.2", 0
sBt93: db "VG8240", 0
sBt94: db "NMS801", 0
sBiosGoauld:  db "GOAULD INTERNA?! (no placa)", 0
