#!/usr/bin/env python3
"""Generate diag/src/bios_table.asm: CRC32 -> machine name for every MSX1/MSX2
main-ROM dump found in the openMSX share/machines folder (plus the Goa'uld's
own internal ROM, which the Doctor must recognise as "not the board").

Usage:  python gen_bios_table.py [openmsx_machines_dir] > ../src/bios_table.asm
"""
import glob, os, re, sys, zlib

MACHINES = sys.argv[1] if len(sys.argv) > 1 else r"C:\Program Files\openMSX\share\machines"

def pretty(fname):
    base = os.path.basename(fname)
    base = re.sub(r"\.rom$", "", base, flags=re.I)
    base = re.sub(r"_?(basic-?bios[12]p?|bios[12]p?)", "", base, flags=re.I)
    base = re.sub(r"^cbios_main_", "C-BIOS ", base, flags=re.I)
    base = base.replace("_", " ").upper()
    return base[:16]

entries = {}
files = sorted(glob.glob(os.path.join(MACHINES, "*bios*.rom")))
files += sorted(glob.glob(os.path.join(MACHINES, "..", "systemroms", "machines", "**", "*bios*.rom"), recursive=True))
for f in files:
    d = open(f, "rb").read()
    if len(d) != 32768:
        continue
    if d[0] != 0xF3 or d[1] != 0xC3:
        continue
    crc = zlib.crc32(d) & 0xFFFFFFFF
    entries.setdefault(crc, []).append(pretty(f))

print("; bios_table.asm - GENERATED by diag/tools/gen_bios_table.py, do not edit")
print(";   CRC32 of 32 KB MSX main ROMs -> name.  dw name, db crc32 LE; dw 0 ends")
print("biosTable:")
names = []
for i, (crc, machs) in enumerate(sorted(entries.items())):
    name = machs[0] + ("+" if len(machs) > 1 else "")
    label = "sBt%d" % i
    names.append((label, name))
    b = crc.to_bytes(4, "little")
    print("    dw %s" % label)
    print("    db 0x%02X, 0x%02X, 0x%02X, 0x%02X       ; %08X %s" % (b[0], b[1], b[2], b[3], crc, ", ".join(machs)))
print("    dw sBiosGoauld")
print("    db 0xE6, 0xAC, 0x09, 0x83       ; 8309ACE6 Goa'uld internal MSX2+ main ROM")
print("    dw 0")
for label, name in names:
    print('%s: db "%s", 0' % (label, name.replace('"', "'")))
print('sBiosGoauld:  db "GOAULD INTERNA?! (no placa)", 0')
print("; %d distinct ROMs" % len(entries), file=sys.stderr)
